name = input("Please enter your name: ").strip()
age = input("Please enter your age: ").strip()
city = input("Please enter your city: ").strip()
goal = input("Please enter your programming goal: ").strip()
print("=======个人名片=======")
print(f"姓名：{name}")
print(f"年龄: {age}" )
print(f"城市:  {city}")
print(f"我的目标: {goal}")
